FROM postgres
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB sql_mq
# COPY init.sql /docker-entrypoint-initdb.d/

# docker build -t sql-mq-db .
# docker run -d --name sql-mq-db-container -p 6666:5432 sql-mq-db